#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
MTFNet public implementation.

This script provides a runnable implementation of the Multi-source Three-branch
Fusion Network (MTFNet) used for fluvial sedimentary facies interpretation. It
supports four functions needed for academic code release:

1. input data-format validation for APMD and TMD CSV files;
2. generation of a small synthetic example dataset;
3. branch pre-training and MTFNet joint fine-tuning;
4. export of model outputs, preprocessing statistics, environment information,
   training histories, confusion matrices, classification reports, and bootstrap
   confidence intervals.

The synthetic example data generated by --make_example_data are provided only to
demonstrate the required data format and the complete training/evaluation
workflow. They are not intended to reproduce the numerical results reported in
the manuscript, which depend on proprietary core-derived and well-log datasets.
"""

import argparse
import json
import math
import random
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
import torch
from sklearn.metrics import classification_report, confusion_matrix, f1_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from torch import nn
from torch.utils.data import DataLoader, Dataset


# Central configuration for data, model architecture, training, and output behavior.
@dataclass
class Config:
    seed: int = 42
    class_names: Tuple[str, ...] = ("BB", "BCH", "BF", "MB", "MCH", "MF")
    num_lithofacies: int = 6
    train_ratio: float = 0.50
    val_ratio: float = 0.20
    test_ratio: float = 0.30
    max_seq_len: int = 12
    image_channels: int = 2
    image_height: int = 64
    image_width: int = 64
    dnn_hidden_dims: Tuple[int, ...] = (64, 32)
    dnn_dropout: float = 0.30
    tf_embed_dim: int = 64
    tf_num_layers: int = 2
    tf_num_heads: int = 4
    tf_ff_dim: int = 128
    tf_dropout: float = 0.20
    cnn_channels: Tuple[int, ...] = (32, 64, 128)
    cnn_kernel_size: int = 3
    cnn_fc_dim: int = 128
    cnn_dropout: float = 0.30
    lambda0: float = 0.60
    batch_size: int = 16
    pretrain_epochs: int = 80
    finetune_epochs: int = 100
    pretrain_lr: float = 1e-3
    finetune_lr: float = 5e-4
    weight_decay: float = 1e-4
    patience: int = 10
    num_workers: int = 0
    bootstrap_n: int = 1000


# Set random seeds and deterministic options for reproducibility.
def set_seed(seed: int) -> None:
    # Fix random states for reproducible experiments.
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True
    try:
        torch.use_deterministic_algorithms(True, warn_only=True)
    except Exception:
        pass


def device_from_arg(name: str) -> torch.device:
    if name == "auto":
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")
    return torch.device(name)


def ensure_dir(path: str | Path) -> Path:
    path = Path(path)
    path.mkdir(parents=True, exist_ok=True)
    return path


def parse_list(value) -> List:
    # Sequence columns should be JSON-style lists, e.g., "[1, 3, 2]".
    if value is None or (isinstance(value, float) and np.isnan(value)):
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, str):
        value = value.strip()
        return json.loads(value) if value else []
    raise TypeError(f"Unsupported list type: {type(value)}")


def infer_feature_cols(df: pd.DataFrame) -> List[str]:
    # LD_* and LF_* are the numerical inputs of the DNN branch.
    ld_cols = sorted([c for c in df.columns if c.startswith("LD_")])
    lf_cols = sorted([c for c in df.columns if c.startswith("LF_")])
    if not ld_cols or not lf_cols:
        raise ValueError("CSV files must contain LD_* and LF_* columns.")
    return ld_cols + lf_cols


def encode_labels(df: pd.DataFrame, class_names: Sequence[str]) -> pd.DataFrame:
    # Convert sedimentary facies labels into integer IDs.
    if "label" not in df.columns:
        raise ValueError("CSV files must contain a 'label' column.")
    mapping = {name: i for i, name in enumerate(class_names)}
    df = df.copy()

    def enc(x):
        if isinstance(x, str):
            x = x.strip()
            if x in mapping:
                return mapping[x]
            if x.isdigit():
                return int(x)
        return int(x)

    df["label_id"] = df["label"].apply(enc)
    if df["label_id"].min() < 0 or df["label_id"].max() >= len(class_names):
        raise ValueError("Labels are outside the class range.")
    return df


def assign_subsets(df: pd.DataFrame, cfg: Config, group_col: Optional[str]) -> pd.DataFrame:
    # Existing train/val/test subset labels are respected.
    # If no subset is supplied, the code creates a split. Group-level splitting avoids well leakage.
    df = df.copy()
    if "subset" in df.columns and df["subset"].notna().all():
        df["subset"] = df["subset"].astype(str).str.lower()
        df["subset"] = df["subset"].replace({"training": "train", "validation": "val", "valid": "val", "testing": "test"})
        if not set(df["subset"].unique()).issubset({"train", "val", "test"}):
            raise ValueError("subset must contain only train, val, or test.")
        return df.reset_index(drop=True)

    if group_col and group_col in df.columns:
        groups = np.array(sorted(df[group_col].dropna().unique()))
        rng = np.random.default_rng(cfg.seed)
        rng.shuffle(groups)
        n = len(groups)
        n_train = max(1, int(round(n * cfg.train_ratio)))
        n_val = max(1, int(round(n * cfg.val_ratio)))
        if n >= 3:
            n_train = min(n_train, n - 2)
            n_val = min(n_val, n - n_train - 1)
        train_g = set(groups[:n_train])
        val_g = set(groups[n_train:n_train + n_val])

        def choose(g):
            if g in train_g:
                return "train"
            if g in val_g:
                return "val"
            return "test"
        df["subset"] = df[group_col].apply(choose)
        return df.reset_index(drop=True)

    train_df, temp_df = train_test_split(df, train_size=cfg.train_ratio, random_state=cfg.seed, stratify=df["label_id"])
    val_ratio_temp = cfg.val_ratio / (cfg.val_ratio + cfg.test_ratio)
    val_df, test_df = train_test_split(temp_df, train_size=val_ratio_temp, random_state=cfg.seed, stratify=temp_df["label_id"])
    train_df, val_df, test_df = train_df.copy(), val_df.copy(), test_df.copy()
    train_df["subset"], val_df["subset"], test_df["subset"] = "train", "val", "test"
    return pd.concat([train_df, val_df, test_df], axis=0).sort_index().reset_index(drop=True)


def part(df: pd.DataFrame, subset: str) -> pd.DataFrame:
    return df[df["subset"].astype(str).str.lower() == subset].reset_index(drop=True)


def dataset_summary(df: pd.DataFrame, class_names: Sequence[str]) -> pd.DataFrame:
    rows = []
    for s in ["train", "val", "test"]:
        d = part(df, s)
        counts = d["label_id"].value_counts().to_dict()
        row = {"subset": s, "Total": len(d)}
        row.update({name: int(counts.get(i, 0)) for i, name in enumerate(class_names)})
        rows.append(row)
    counts = df["label_id"].value_counts().to_dict()
    row = {"subset": "Total", "Total": len(df)}
    row.update({name: int(counts.get(i, 0)) for i, name in enumerate(class_names)})
    rows.append(row)
    return pd.DataFrame(rows)


def validate_dataframe(df: pd.DataFrame, name: str, cfg: Config, require_image: bool = False) -> None:
    """Validate the minimum CSV schema required by MTFNet.

    Required columns for both APMD and TMD:
        label, LD_*, LF_*, seq_ids, seq_thick
    Additional required column for TMD:
        image_path

    seq_ids and seq_thick must be JSON-style lists. Lithofacies IDs are expected
    to be integers from 1 to cfg.num_lithofacies. The value 0 is reserved for
    sequence padding inside the model.
    """
    required = ["label", "seq_ids", "seq_thick"]
    if require_image:
        required.append("image_path")
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"{name} is missing required columns: {missing}")

    ld_cols = sorted([c for c in df.columns if c.startswith("LD_")])
    lf_cols = sorted([c for c in df.columns if c.startswith("LF_")])
    if not ld_cols or not lf_cols:
        raise ValueError(f"{name} must contain LD_* and LF_* columns.")
    if len(ld_cols) != len(lf_cols):
        raise ValueError(f"{name} should contain the same number of LD_* and LF_* columns.")

    if "subset" in df.columns and df["subset"].notna().any():
        values = set(df["subset"].dropna().astype(str).str.lower().replace({"training": "train", "validation": "val", "valid": "val", "testing": "test"}).unique())
        if not values.issubset({"train", "val", "test"}):
            raise ValueError(f"{name}.subset must contain only train, val, or test.")

    for i, row in df.iterrows():
        seq_ids = parse_list(row["seq_ids"])
        seq_thick = parse_list(row["seq_thick"])
        if len(seq_ids) == 0:
            raise ValueError(f"{name} row {i}: seq_ids is empty.")
        if len(seq_ids) != len(seq_thick):
            raise ValueError(f"{name} row {i}: seq_ids and seq_thick must have the same length.")
        for litho_id in seq_ids:
            litho_id = int(litho_id)
            if litho_id < 1 or litho_id > cfg.num_lithofacies:
                raise ValueError(
                    f"{name} row {i}: lithofacies ID {litho_id} is outside "
                    f"the valid range [1, {cfg.num_lithofacies}]."
                )

    if require_image:
        missing_paths = [str(p) for p in df["image_path"].head(10) if not Path(str(p)).expanduser().exists()]
        if missing_paths:
            raise FileNotFoundError(
                f"{name} contains image_path values that cannot be found. "
                f"Examples: {missing_paths[:3]}"
            )


def resolve_image_paths(df: pd.DataFrame, csv_path: str | Path) -> pd.DataFrame:
    """Resolve relative image paths against the directory of the CSV file."""
    df = df.copy()
    if "image_path" not in df.columns:
        return df
    base = Path(csv_path).expanduser().resolve().parent

    def resolve_one(value):
        path = Path(str(value)).expanduser()
        if path.is_absolute():
            return str(path)
        return str((base / path).resolve())

    df["image_path"] = df["image_path"].apply(resolve_one)
    return df


def save_environment(outdir: Path) -> None:
    env = {
        "python": sys.version,
        "numpy": np.__version__,
        "pandas": pd.__version__,
        "torch": torch.__version__,
        "cuda_available": torch.cuda.is_available(),
        "cuda_version": torch.version.cuda,
        "platform": sys.platform,
    }
    (outdir / "environment.json").write_text(json.dumps(env, indent=2), encoding="utf-8")


def save_preprocessor(pp: "Preprocessor", outdir: Path) -> None:
    stats = {
        "feature_cols": pp.feature_cols,
        "thick_mean": pp.thick_mean,
        "thick_std": pp.thick_std,
        "image_mean": pp.image_mean.tolist(),
        "image_std": pp.image_std.tolist(),
        "scaler_mean": pp.scaler.mean_.tolist(),
        "scaler_scale": pp.scaler.scale_.tolist(),
    }
    (outdir / "preprocessor_stats.json").write_text(json.dumps(stats, indent=2), encoding="utf-8")


def bootstrap_f1_ci(y_true, y_pred, class_names: Sequence[str], n_bootstrap: int = 1000, seed: int = 42) -> pd.DataFrame:
    """Return percentile bootstrap confidence intervals for class and macro F1.

    This resamples the evaluated test predictions. It is intended as a transparent
    implementation of the uncertainty calculation used for reporting model
    performance. For very small test subsets, class-level intervals should be
    interpreted cautiously.
    """
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    rng = np.random.default_rng(seed)
    labels = np.arange(len(class_names))
    rows = []

    if len(y_true) == 0:
        return pd.DataFrame(columns=["facies", "f1_mean", "ci_lower", "ci_upper"])

    macro_scores = []
    class_scores = {name: [] for name in class_names}
    for _ in range(n_bootstrap):
        idx = rng.choice(len(y_true), size=len(y_true), replace=True)
        yt, yp = y_true[idx], y_pred[idx]
        macro_scores.append(f1_score(yt, yp, labels=labels, average="macro", zero_division=0))
        per_class = f1_score(yt, yp, labels=labels, average=None, zero_division=0)
        for i, name in enumerate(class_names):
            class_scores[name].append(per_class[i])

    for name in class_names:
        scores = np.asarray(class_scores[name], dtype=float)
        rows.append({
            "facies": name,
            "f1_mean": float(np.mean(scores)),
            "ci_lower": float(np.percentile(scores, 2.5)),
            "ci_upper": float(np.percentile(scores, 97.5)),
        })
    scores = np.asarray(macro_scores, dtype=float)
    rows.append({
        "facies": "macro avg",
        "f1_mean": float(np.mean(scores)),
        "ci_lower": float(np.percentile(scores, 2.5)),
        "ci_upper": float(np.percentile(scores, 97.5)),
    })
    return pd.DataFrame(rows)


def create_example_data(outdir: Path, cfg: Config) -> None:
    """Create a small synthetic dataset that matches the required file format.

    The example data are synthetic and are only intended to verify that the
    public code can run end-to-end. They are not geological measurements and
    should not be used to evaluate model accuracy reported in the manuscript.
    """
    rng = np.random.default_rng(cfg.seed)
    outdir = ensure_dir(outdir)
    image_dir = ensure_dir(outdir / "images")
    ld_cols = [f"LD_{i}" for i in range(1, cfg.num_lithofacies + 1)]
    lf_cols = [f"LF_{i}" for i in range(1, cfg.num_lithofacies + 1)]
    subsets_apmd = ["train", "train", "val", "test"]
    subsets_tmd = ["train", "train", "val", "test"]

    def make_features(class_id):
        base = np.ones(cfg.num_lithofacies) * 0.6
        base[class_id % cfg.num_lithofacies] += 3.0
        base[(class_id + 1) % cfg.num_lithofacies] += 1.2
        ld = rng.dirichlet(base)
        lf = rng.dirichlet(base + rng.uniform(0.0, 0.4, cfg.num_lithofacies))
        return ld, lf

    def make_sequence(class_id):
        length = int(rng.integers(4, min(cfg.max_seq_len, 9) + 1))
        primary = (class_id % cfg.num_lithofacies) + 1
        secondary = ((class_id + 1) % cfg.num_lithofacies) + 1
        ids = rng.choice([primary, secondary, int(rng.integers(1, cfg.num_lithofacies + 1))], size=length, p=[0.50, 0.35, 0.15]).astype(int).tolist()
        thick = np.round(rng.uniform(0.2, 2.5, size=length), 3).tolist()
        return ids, thick

    def make_image(class_id, sample_id):
        h, w = cfg.image_height, cfg.image_width
        x = np.linspace(0, 1, w, dtype=np.float32)[None, :]
        y = np.linspace(0, 1, h, dtype=np.float32)[:, None]
        arr = np.zeros((cfg.image_channels, h, w), dtype=np.float32)
        for ch in range(cfg.image_channels):
            signal = 0.25 + 0.08 * class_id + 0.10 * np.sin((class_id + ch + 1) * math.pi * x) + 0.10 * np.cos((class_id + 1) * math.pi * y)
            noise = rng.normal(0, 0.03, size=(h, w)).astype(np.float32)
            arr[ch] = np.clip(signal + noise, 0, 1)
        name = f"sample_{sample_id:04d}.npy"
        np.save(image_dir / name, arr)
        return str(Path("images") / name)

    def build_rows(rows_per_class, include_image):
        rows = []
        sample_id = 0
        for class_id, class_name in enumerate(cfg.class_names):
            for subset in rows_per_class:
                ld, lf = make_features(class_id)
                seq_ids, seq_thick = make_sequence(class_id)
                row = {
                    "sample_id": f"{class_name}_{sample_id:04d}",
                    "well_id": f"W{class_id + 1:02d}_{sample_id % 3}",
                    "subset": subset,
                    "label": class_name,
                    "seq_ids": json.dumps(seq_ids),
                    "seq_thick": json.dumps(seq_thick),
                }
                row.update({c: float(v) for c, v in zip(ld_cols, ld)})
                row.update({c: float(v) for c, v in zip(lf_cols, lf)})
                if include_image:
                    row["image_path"] = make_image(class_id, sample_id)
                rows.append(row)
                sample_id += 1
        return pd.DataFrame(rows)

    apmd = build_rows(subsets_apmd, include_image=False)
    tmd = build_rows(subsets_tmd, include_image=True)
    apmd.to_csv(outdir / "apmd_example.csv", index=False)
    tmd.to_csv(outdir / "tmd_example.csv", index=False)

    schema = {
        "description": "Synthetic example data for testing the MTFNet workflow.",
        "required_columns_apmd": ["label", "subset", "LD_*", "LF_*", "seq_ids", "seq_thick"],
        "required_columns_tmd": ["label", "subset", "LD_*", "LF_*", "seq_ids", "seq_thick", "image_path"],
        "label_values": list(cfg.class_names),
        "note": "These example data are synthetic and do not reproduce manuscript results.",
    }
    (outdir / "schema.json").write_text(json.dumps(schema, indent=2), encoding="utf-8")
    print(f"Synthetic example data written to: {outdir}")
    print(f"APMD CSV: {outdir / 'apmd_example.csv'}")
    print(f"TMD CSV: {outdir / 'tmd_example.csv'}")


class Preprocessor:
    def __init__(self, feature_cols, scaler, thick_mean, thick_std, image_mean, image_std):
        self.feature_cols = feature_cols
        self.scaler = scaler
        self.thick_mean = thick_mean
        self.thick_std = thick_std
        self.image_mean = image_mean.astype(np.float32)
        self.image_std = image_std.astype(np.float32)


def load_image(path: str | Path, channels: int) -> np.ndarray:
    # Recommended input image format: .npy with shape [C, H, W].
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Image file not found: {path}")
    if path.suffix.lower() == ".npy":
        arr = np.load(path).astype(np.float32)
    else:
        from PIL import Image
        arr = np.asarray(Image.open(path)).astype(np.float32)
        if arr.max() > 1.0:
            arr = arr / 255.0
    if arr.ndim == 2:
        arr = arr[None, :, :]
    elif arr.ndim == 3 and arr.shape[0] not in {1, 2, 3, 4}:
        arr = np.transpose(arr, (2, 0, 1))
    if arr.ndim != 3:
        raise ValueError(f"Unsupported image shape: {arr.shape}")
    if arr.shape[0] < channels:
        arr = np.concatenate([arr, np.repeat(arr[-1:], channels - arr.shape[0], axis=0)], axis=0)
    return arr[:channels].astype(np.float32)


def resize_image(arr: np.ndarray, height: int, width: int) -> np.ndarray:
    x = torch.tensor(arr, dtype=torch.float32).unsqueeze(0)
    x = torch.nn.functional.interpolate(x, size=(height, width), mode="bilinear", align_corners=False)
    return x.squeeze(0).numpy().astype(np.float32)


# Fit preprocessing statistics using training data only to avoid data leakage.
def fit_preprocessor(apmd: pd.DataFrame, tmd: pd.DataFrame, feature_cols: List[str], cfg: Config) -> Preprocessor:
    # All preprocessing statistics are fitted on training samples only.
    train_num_seq = pd.concat([part(apmd, "train"), part(tmd, "train")], axis=0)
    scaler = StandardScaler().fit(train_num_seq[feature_cols].values.astype(np.float32))

    thickness = []
    if "seq_thick" in train_num_seq.columns:
        for v in train_num_seq["seq_thick"]:
            thickness += [float(x) for x in parse_list(v)]
    if not thickness:
        thickness = [1.0]
    thick_mean = float(np.mean(thickness))
    thick_std = float(np.std(thickness) + 1e-6)

    if "image_path" not in tmd.columns:
        raise ValueError("TMD must contain image_path for CNN and MTFNet training.")
    sums = np.zeros(cfg.image_channels, dtype=np.float64)
    squares = np.zeros(cfg.image_channels, dtype=np.float64)
    pixels = 0
    for p in part(tmd, "train")["image_path"]:
        img = load_image(p, cfg.image_channels)
        if img.shape[1:] != (cfg.image_height, cfg.image_width):
            img = resize_image(img, cfg.image_height, cfg.image_width)
        flat = img.reshape(cfg.image_channels, -1)
        sums += flat.sum(axis=1)
        squares += (flat ** 2).sum(axis=1)
        pixels += flat.shape[1]
    mean = sums / max(pixels, 1)
    var = squares / max(pixels, 1) - mean ** 2
    std = np.sqrt(np.maximum(var, 1e-6))
    return Preprocessor(feature_cols, scaler, thick_mean, thick_std, mean, std)


# Dataset used for single-branch pre-training.
# DNN receives LD/LF; TF receives lithofacies sequences; CNN receives GR-SP images.
class BranchDataset(Dataset):
    def __init__(self, df: pd.DataFrame, modality: str, pp: Preprocessor, cfg: Config):
        self.df = df.reset_index(drop=True)
        self.modality = modality
        self.pp = pp
        self.cfg = cfg
        if modality not in {"dnn", "tf", "cnn"}:
            raise ValueError("modality must be dnn, tf, or cnn.")

    def __len__(self):
        return len(self.df)

    def num_x(self, row):
        x = row[self.pp.feature_cols].values.astype(np.float32).reshape(1, -1)
        return self.pp.scaler.transform(x).squeeze(0).astype(np.float32)

    def seq_x(self, row):
        ids = [int(x) for x in parse_list(row["seq_ids"])]
        thick = [float(x) for x in parse_list(row["seq_thick"])] if "seq_thick" in row and not pd.isna(row["seq_thick"]) else [1.0] * len(ids)
        if len(thick) != len(ids):
            thick = [1.0] * len(ids)
        ids, thick = ids[:self.cfg.max_seq_len], thick[:self.cfg.max_seq_len]
        L = len(ids)
        seq_ids = np.zeros(self.cfg.max_seq_len, dtype=np.int64)
        seq_thick = np.zeros(self.cfg.max_seq_len, dtype=np.float32)
        seq_mask = np.zeros(self.cfg.max_seq_len, dtype=np.bool_)
        if L:
            seq_ids[:L] = np.asarray(ids, dtype=np.int64)
            seq_thick[:L] = (np.asarray(thick, dtype=np.float32) - self.pp.thick_mean) / self.pp.thick_std
            seq_mask[:L] = True
        return seq_ids, seq_thick, seq_mask

    def image_x(self, row):
        img = load_image(row["image_path"], self.cfg.image_channels)
        if img.shape[1:] != (self.cfg.image_height, self.cfg.image_width):
            img = resize_image(img, self.cfg.image_height, self.cfg.image_width)
        img = (img - self.pp.image_mean.reshape(-1, 1, 1)) / self.pp.image_std.reshape(-1, 1, 1)
        return img.astype(np.float32)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        item = {"y": np.int64(row["label_id"])}
        if self.modality == "dnn":
            item["x_num"] = self.num_x(row)
        elif self.modality == "tf":
            item["seq_ids"], item["seq_thick"], item["seq_mask"] = self.seq_x(row)
        else:
            item["image"] = self.image_x(row)
        return item


# Dataset used for MTFNet joint fine-tuning.
# Only TMD samples should be used here because complete multimodal alignment is required.
class MultiModalDataset(Dataset):
    def __init__(self, df: pd.DataFrame, pp: Preprocessor, cfg: Config):
        self.df = df.reset_index(drop=True)
        self.helper = BranchDataset(self.df, "dnn", pp, cfg)

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        seq_ids, seq_thick, seq_mask = self.helper.seq_x(row)
        return {
            "x_num": self.helper.num_x(row),
            "seq_ids": seq_ids,
            "seq_thick": seq_thick,
            "seq_mask": seq_mask,
            "image": self.helper.image_x(row),
            "y": np.int64(row["label_id"]),
        }


def collate(batch):
    out = {}
    for k in batch[0].keys():
        vals = [b[k] for b in batch]
        if k == "y":
            out[k] = torch.tensor(vals, dtype=torch.long)
        elif k == "seq_ids":
            out[k] = torch.tensor(np.stack(vals), dtype=torch.long)
        elif k == "seq_mask":
            out[k] = torch.tensor(np.stack(vals), dtype=torch.bool)
        else:
            out[k] = torch.tensor(np.stack(vals), dtype=torch.float32)
    return out


def loader(ds: Dataset, cfg: Config, shuffle: bool):
    return DataLoader(ds, batch_size=cfg.batch_size, shuffle=shuffle, num_workers=cfg.num_workers, collate_fn=collate)


def to_device(batch, device):
    return {k: v.to(device) for k, v in batch.items()}


# DNN branch for lithofacies statistical parameters, i.e., LD and LF.
class DNNBranch(nn.Module):
    def __init__(self, input_dim, hidden_dims, dropout, num_classes):
        super().__init__()
        layers, d = [], input_dim
        for h in hidden_dims:
            layers += [nn.Linear(d, h), nn.ReLU(), nn.Dropout(dropout)]
            d = h
        layers.append(nn.Linear(d, num_classes))
        self.net = nn.Sequential(*layers)

    def forward(self, x_num):
        return self.net(x_num)


# Transformer branch for lithofacies stacking sequences.
# Lithofacies type, thickness, and position are jointly encoded for each token.
class TFBranch(nn.Module):
    def __init__(self, cfg: Config, num_classes: int):
        super().__init__()
        self.litho_emb = nn.Embedding(cfg.num_lithofacies + 1, cfg.tf_embed_dim, padding_idx=0)
        self.thick_emb = nn.Linear(1, cfg.tf_embed_dim)
        self.pos_emb = nn.Embedding(cfg.max_seq_len, cfg.tf_embed_dim)
        layer = nn.TransformerEncoderLayer(cfg.tf_embed_dim, cfg.tf_num_heads, cfg.tf_ff_dim, cfg.tf_dropout, batch_first=True, norm_first=True)
        self.encoder = nn.TransformerEncoder(layer, cfg.tf_num_layers)
        self.drop = nn.Dropout(cfg.tf_dropout)
        self.cls = nn.Linear(cfg.tf_embed_dim, num_classes)

    def forward(self, seq_ids, seq_thick, seq_mask):
        B, L = seq_ids.shape
        pos = torch.arange(L, device=seq_ids.device).unsqueeze(0).expand(B, L)
        x = self.litho_emb(seq_ids) + self.thick_emb(seq_thick.unsqueeze(-1)) + self.pos_emb(pos)
        h = self.encoder(x, src_key_padding_mask=~seq_mask)
        m = seq_mask.unsqueeze(-1).float()
        h = (h * m).sum(dim=1) / m.sum(dim=1).clamp_min(1.0)
        return self.cls(self.drop(h))


# CNN branch for GR-SP well-log curve images.
# It extracts local curve morphology and repeated response patterns.
class CNNBranch(nn.Module):
    def __init__(self, cfg: Config, num_classes: int):
        super().__init__()
        layers, c = [], cfg.image_channels
        pad = cfg.cnn_kernel_size // 2
        for oc in cfg.cnn_channels:
            layers += [nn.Conv2d(c, oc, cfg.cnn_kernel_size, padding=pad), nn.BatchNorm2d(oc), nn.ReLU(), nn.MaxPool2d(2)]
            c = oc
        self.conv = nn.Sequential(*layers)
        self.head = nn.Sequential(nn.AdaptiveAvgPool2d((1, 1)), nn.Flatten(), nn.Linear(c, cfg.cnn_fc_dim), nn.ReLU(), nn.Dropout(cfg.cnn_dropout), nn.Linear(cfg.cnn_fc_dim, num_classes))

    def forward(self, image):
        return self.head(self.conv(image))


# Multi-source Three-branch Fusion Network.
# The three branch logits are adaptively combined at the logit level.
class MTFNet(nn.Module):
    def __init__(self, dnn: DNNBranch, tf: TFBranch, cnn: CNNBranch, num_classes: int):
        super().__init__()
        self.dnn, self.tf, self.cnn = dnn, tf, cnn
        self.theta = nn.Parameter(torch.zeros(3))
        self.bias = nn.Parameter(torch.zeros(num_classes))

    def fusion_weights(self):
        return torch.softmax(self.theta, dim=0)

    def forward(self, x_num, seq_ids, seq_thick, seq_mask, image):
        z_dnn = self.dnn(x_num)
        z_tf = self.tf(seq_ids, seq_thick, seq_mask)
        z_cnn = self.cnn(image)
        alpha = self.fusion_weights()
        z = alpha[0] * z_dnn + alpha[1] * z_tf + alpha[2] * z_cnn + self.bias
        return {"z_dnn": z_dnn, "z_tf": z_tf, "z_cnn": z_cnn, "z_fuse": z, "alpha": alpha}


def logits_for_branch(model, modality, batch):
    if modality == "dnn":
        return model(batch["x_num"])
    if modality == "tf":
        return model(batch["seq_ids"], batch["seq_thick"], batch["seq_mask"])
    if modality == "cnn":
        return model(batch["image"])
    raise ValueError(modality)


def metrics(y_true, y_pred, probs, class_names, loss):
    report = classification_report(y_true, y_pred, labels=list(range(len(class_names))), target_names=list(class_names), output_dict=True, zero_division=0)
    cm = confusion_matrix(y_true, y_pred, labels=list(range(len(class_names))))
    return {"loss": float(loss), "report": report, "confusion_matrix": cm, "y_true": np.asarray(y_true), "y_pred": np.asarray(y_pred), "probabilities": probs}


@torch.no_grad()
def evaluate_branch(model, data_loader, modality, device, class_names):
    model.eval()
    ce = nn.CrossEntropyLoss()
    y_true, y_pred, probs = [], [], []
    loss_sum, n = 0.0, 0
    for batch in data_loader:
        batch = to_device(batch, device)
        z = logits_for_branch(model, modality, batch)
        loss = ce(z, batch["y"])
        p = torch.softmax(z, dim=1)
        pred = p.argmax(dim=1)
        loss_sum += loss.item() * len(batch["y"])
        n += len(batch["y"])
        y_true.extend(batch["y"].cpu().numpy())
        y_pred.extend(pred.cpu().numpy())
        probs.append(p.cpu().numpy())
    probs = np.concatenate(probs, axis=0) if probs else np.empty((0, len(class_names)))
    return metrics(y_true, y_pred, probs, class_names, loss_sum / max(n, 1))


@torch.no_grad()
def evaluate_mtfnet(model, data_loader, device, class_names):
    model.eval()
    ce = nn.CrossEntropyLoss()
    y_true, y_pred, probs, alphas = [], [], [], []
    loss_sum, n = 0.0, 0
    for batch in data_loader:
        batch = to_device(batch, device)
        out = model(batch["x_num"], batch["seq_ids"], batch["seq_thick"], batch["seq_mask"], batch["image"])
        loss = ce(out["z_fuse"], batch["y"])
        p = torch.softmax(out["z_fuse"], dim=1)
        pred = p.argmax(dim=1)
        loss_sum += loss.item() * len(batch["y"])
        n += len(batch["y"])
        y_true.extend(batch["y"].cpu().numpy())
        y_pred.extend(pred.cpu().numpy())
        probs.append(p.cpu().numpy())
        alphas.append(out["alpha"].cpu().numpy())
    probs = np.concatenate(probs, axis=0) if probs else np.empty((0, len(class_names)))
    out = metrics(y_true, y_pred, probs, class_names, loss_sum / max(n, 1))
    out["alpha"] = np.mean(np.stack(alphas), axis=0) if alphas else np.zeros(3)
    return out


def save_metrics(result, outdir: Path, prefix: str, class_names, n_bootstrap: int = 1000, seed: int = 42):
    pd.DataFrame(result["report"]).T.to_csv(outdir / f"{prefix}_classification_report.csv")
    pd.DataFrame(result["confusion_matrix"], index=class_names, columns=class_names).to_csv(outdir / f"{prefix}_confusion_matrix.csv")
    pred = pd.DataFrame({"y_true": result["y_true"], "y_pred": result["y_pred"], "y_true_name": [class_names[i] for i in result["y_true"]], "y_pred_name": [class_names[i] for i in result["y_pred"]]})
    for i, name in enumerate(class_names):
        pred[f"prob_{name}"] = result["probabilities"][:, i] if len(result["probabilities"]) else []
    pred.to_csv(outdir / f"{prefix}_predictions.csv", index=False)
    if "alpha" in result:
        pd.DataFrame([{"alpha_DNN": result["alpha"][0], "alpha_TF": result["alpha"][1], "alpha_CNN": result["alpha"][2]}]).to_csv(outdir / f"{prefix}_alpha.csv", index=False)
    bootstrap_f1_ci(result["y_true"], result["y_pred"], class_names, n_bootstrap=n_bootstrap, seed=seed).to_csv(outdir / f"{prefix}_bootstrap_f1_ci.csv", index=False)


# Stage 1: independently pre-train one branch using its own input modality.
def train_branch(model, modality, train_loader, val_loader, test_loader, cfg, device, class_names, outdir):
    model.to(device)
    ce = nn.CrossEntropyLoss()
    opt = torch.optim.Adam(model.parameters(), lr=cfg.pretrain_lr, weight_decay=cfg.weight_decay)
    best, patience_count, hist = float("inf"), 0, []
    for epoch in range(1, cfg.pretrain_epochs + 1):
        model.train()
        loss_sum, n = 0.0, 0
        for batch in train_loader:
            batch = to_device(batch, device)
            opt.zero_grad(set_to_none=True)
            loss = ce(logits_for_branch(model, modality, batch), batch["y"])
            loss.backward()
            opt.step()
            loss_sum += loss.item() * len(batch["y"])
            n += len(batch["y"])
        val = evaluate_branch(model, val_loader, modality, device, class_names)
        hist.append({"epoch": epoch, "train_loss": loss_sum / max(n, 1), "val_loss": val["loss"], "val_macro_f1": val["report"]["macro avg"]["f1-score"]})
        if val["loss"] < best:
            best, patience_count = val["loss"], 0
            torch.save(model.state_dict(), outdir / f"best_{modality}.pt")
        else:
            patience_count += 1
            if patience_count >= cfg.patience:
                break
    model.load_state_dict(torch.load(outdir / f"best_{modality}.pt", map_location=device))
    pd.DataFrame(hist).to_csv(outdir / f"{modality}_history.csv", index=False)
    save_metrics(evaluate_branch(model, test_loader, modality, device, class_names), outdir, f"{modality}_test", class_names, n_bootstrap=cfg.bootstrap_n, seed=cfg.seed)
    return model


def dynamic_lambdas(previous_alpha, lambda0, device):
    # lambda_i(t) is updated from alpha_i(t-1).
    if previous_alpha is None:
        return torch.full((3,), lambda0 / 3.0, device=device)
    numerator = 1.0 - previous_alpha.detach().to(device)
    return (lambda0 * numerator / numerator.sum().clamp_min(1e-8)).detach()


# Stage 2: jointly fine-tune MTFNet using TMD only.
# The fused-output loss and branch-level auxiliary losses are optimized together.
def train_mtfnet(model, train_loader, val_loader, test_loader, cfg, device, class_names, outdir):
    model.to(device)
    ce = nn.CrossEntropyLoss()
    opt = torch.optim.Adam(model.parameters(), lr=cfg.finetune_lr, weight_decay=cfg.weight_decay)
    best, patience_count, prev_alpha, hist = float("inf"), 0, None, []
    for epoch in range(1, cfg.finetune_epochs + 1):
        lambdas = dynamic_lambdas(prev_alpha, cfg.lambda0, device)
        model.train()
        loss_sum, n = 0.0, 0
        for batch in train_loader:
            batch = to_device(batch, device)
            opt.zero_grad(set_to_none=True)
            out = model(batch["x_num"], batch["seq_ids"], batch["seq_thick"], batch["seq_mask"], batch["image"])
            y = batch["y"]
            loss_fuse = ce(out["z_fuse"], y)
            loss_dnn = ce(out["z_dnn"], y)
            loss_tf = ce(out["z_tf"], y)
            loss_cnn = ce(out["z_cnn"], y)
            # Total loss = fused-output loss + dynamically weighted branch auxiliary losses.
            loss = loss_fuse + lambdas[0] * loss_dnn + lambdas[1] * loss_tf + lambdas[2] * loss_cnn
            loss.backward()
            opt.step()
            loss_sum += loss.item() * len(y)
            n += len(y)
        alpha = model.fusion_weights().detach().clone()
        prev_alpha = alpha
        val = evaluate_mtfnet(model, val_loader, device, class_names)
        hist.append({"epoch": epoch, "train_loss": loss_sum / max(n, 1), "val_loss": val["loss"], "val_macro_f1": val["report"]["macro avg"]["f1-score"], "alpha_DNN": float(alpha[0].cpu()), "alpha_TF": float(alpha[1].cpu()), "alpha_CNN": float(alpha[2].cpu()), "lambda_DNN": float(lambdas[0].cpu()), "lambda_TF": float(lambdas[1].cpu()), "lambda_CNN": float(lambdas[2].cpu())})
        if val["loss"] < best:
            best, patience_count = val["loss"], 0
            torch.save(model.state_dict(), outdir / "best_mtfnet.pt")
        else:
            patience_count += 1
            if patience_count >= cfg.patience:
                break
    model.load_state_dict(torch.load(outdir / "best_mtfnet.pt", map_location=device))
    pd.DataFrame(hist).to_csv(outdir / "mtfnet_history.csv", index=False)
    save_metrics(evaluate_mtfnet(model, test_loader, device, class_names), outdir, "mtfnet_test", class_names, n_bootstrap=cfg.bootstrap_n, seed=cfg.seed)
    return model


def merge_subsets(apmd, tmd, subset):
    return pd.concat([part(apmd, subset), part(tmd, subset)], axis=0).reset_index(drop=True)


def build_models(input_dim, cfg):
    n = len(cfg.class_names)
    dnn = DNNBranch(input_dim, cfg.dnn_hidden_dims, cfg.dnn_dropout, n)
    tf = TFBranch(cfg, n)
    cnn = CNNBranch(cfg, n)
    return dnn, tf, cnn


def run(args):
    cfg = Config(
        seed=args.seed,
        class_names=tuple(x.strip() for x in args.class_names.split(",") if x.strip()),
        num_lithofacies=args.num_lithofacies,
        max_seq_len=args.max_seq_len,
        image_height=args.image_height,
        image_width=args.image_width,
        lambda0=args.lambda0,
        batch_size=args.batch_size,
        pretrain_epochs=args.pretrain_epochs,
        finetune_epochs=args.finetune_epochs,
        pretrain_lr=args.pretrain_lr,
        finetune_lr=args.finetune_lr,
        weight_decay=args.weight_decay,
        patience=args.patience,
        num_workers=args.num_workers,
        bootstrap_n=args.bootstrap_n,
    )
    if args.lite:
        cfg.dnn_hidden_dims = (16,)
        cfg.tf_embed_dim = 16
        cfg.tf_num_layers = 1
        cfg.tf_num_heads = 2
        cfg.tf_ff_dim = 32
        cfg.cnn_channels = (8, 16)
        cfg.cnn_fc_dim = 32
    if args.torch_threads > 0:
        torch.set_num_threads(args.torch_threads)
    set_seed(cfg.seed)

    if args.make_example_data:
        create_example_data(Path(args.make_example_data), cfg)
        return

    if not args.apmd_csv or not args.tmd_csv:
        raise ValueError("--apmd_csv and --tmd_csv are required unless --make_example_data is used.")

    device = device_from_arg(args.device)
    outdir = ensure_dir(args.outdir)
    save_environment(outdir)
    (outdir / "config.json").write_text(json.dumps(asdict(cfg), indent=2), encoding="utf-8")

    apmd_raw = pd.read_csv(args.apmd_csv)
    tmd_raw = resolve_image_paths(pd.read_csv(args.tmd_csv), args.tmd_csv)

    validate_dataframe(apmd_raw, "APMD", cfg, require_image=False)
    validate_dataframe(tmd_raw, "TMD", cfg, require_image=True)

    apmd = assign_subsets(encode_labels(apmd_raw, cfg.class_names), cfg, args.apmd_group_col or None)
    tmd_group = args.tmd_group_col if args.tmd_group_col else ("well_id" if "well_id" in tmd_raw.columns else None)
    tmd = assign_subsets(encode_labels(tmd_raw, cfg.class_names), cfg, tmd_group)

    feature_cols = infer_feature_cols(pd.concat([apmd, tmd], axis=0, ignore_index=True))
    pp = fit_preprocessor(apmd, tmd, feature_cols, cfg)
    save_preprocessor(pp, outdir)
    dataset_summary(apmd, cfg.class_names).to_csv(outdir / "apmd_summary.csv", index=False)
    dataset_summary(tmd, cfg.class_names).to_csv(outdir / "tmd_summary.csv", index=False)
    pd.DataFrame({"feature": feature_cols}).to_csv(outdir / "ld_lf_features.csv", index=False)

    dnn, tf, cnn = build_models(len(feature_cols), cfg)

    dnn = train_branch(
        dnn,
        "dnn",
        loader(BranchDataset(merge_subsets(apmd, tmd, "train"), "dnn", pp, cfg), cfg, True),
        loader(BranchDataset(merge_subsets(apmd, tmd, "val"), "dnn", pp, cfg), cfg, False),
        loader(BranchDataset(merge_subsets(apmd, tmd, "test"), "dnn", pp, cfg), cfg, False),
        cfg,
        device,
        cfg.class_names,
        ensure_dir(outdir / "DNN_branch"),
    )
    tf = train_branch(
        tf,
        "tf",
        loader(BranchDataset(merge_subsets(apmd, tmd, "train"), "tf", pp, cfg), cfg, True),
        loader(BranchDataset(merge_subsets(apmd, tmd, "val"), "tf", pp, cfg), cfg, False),
        loader(BranchDataset(merge_subsets(apmd, tmd, "test"), "tf", pp, cfg), cfg, False),
        cfg,
        device,
        cfg.class_names,
        ensure_dir(outdir / "TF_branch"),
    )
    cnn = train_branch(
        cnn,
        "cnn",
        loader(BranchDataset(part(tmd, "train"), "cnn", pp, cfg), cfg, True),
        loader(BranchDataset(part(tmd, "val"), "cnn", pp, cfg), cfg, False),
        loader(BranchDataset(part(tmd, "test"), "cnn", pp, cfg), cfg, False),
        cfg,
        device,
        cfg.class_names,
        ensure_dir(outdir / "CNN_branch"),
    )

    mtfnet = MTFNet(dnn, tf, cnn, len(cfg.class_names))
    mtfnet = train_mtfnet(
        mtfnet,
        loader(MultiModalDataset(part(tmd, "train"), pp, cfg), cfg, True),
        loader(MultiModalDataset(part(tmd, "val"), pp, cfg), cfg, False),
        loader(MultiModalDataset(part(tmd, "test"), pp, cfg), cfg, False),
        cfg,
        device,
        cfg.class_names,
        ensure_dir(outdir / "MTFNet"),
    )
    torch.save(mtfnet.state_dict(), outdir / "MTFNet_final.pt")


def parser():
    p = argparse.ArgumentParser(
        description=(
            "MTFNet public implementation for fluvial sedimentary facies interpretation. "
            "The script can generate synthetic example data and run the full "
            "branch-pretraining, joint-finetuning, and evaluation workflow."
        )
    )
    p.add_argument("--make_example_data", default="", help="Directory in which a small synthetic example dataset will be created, then exit.")
    p.add_argument("--apmd_csv", default="", help="Path to APMD CSV: LD/LF, lithofacies sequences, and labels. Required unless --make_example_data is used.")
    p.add_argument("--tmd_csv", default="", help="Path to TMD CSV: LD/LF, lithofacies sequences, image_path, and labels. Required unless --make_example_data is used.")
    p.add_argument("--outdir", default="runs/MTFNet", help="Directory for model checkpoints, histories, predictions, metrics, and environment files.")
    p.add_argument("--device", default="auto", help="Device name: auto, cpu, cuda, or cuda:0.")
    p.add_argument("--class_names", default="BB,BCH,BF,MB,MCH,MF", help="Comma-separated sedimentary facies class names in label order.")
    p.add_argument("--num_lithofacies", type=int, default=6, help="Number of lithofacies types. IDs in seq_ids must be 1..num_lithofacies; 0 is reserved for padding.")
    p.add_argument("--apmd_group_col", default="", help="Optional grouping column for APMD splitting. Existing subset labels are respected when present.")
    p.add_argument("--tmd_group_col", default="well_id", help="Optional grouping column for TMD splitting, used to reduce well-level leakage. Existing subset labels are respected when present.")
    p.add_argument("--seed", type=int, default=42, help="Random seed.")
    p.add_argument("--max_seq_len", type=int, default=12, help="Maximum lithofacies sequence length after truncation/padding.")
    p.add_argument("--image_height", type=int, default=64, help="Image height after resizing.")
    p.add_argument("--image_width", type=int, default=64, help="Image width after resizing.")
    p.add_argument("--lambda0", type=float, default=0.60, help="Overall coefficient for dynamic auxiliary supervision.")
    p.add_argument("--batch_size", type=int, default=16, help="Mini-batch size.")
    p.add_argument("--pretrain_epochs", type=int, default=80, help="Maximum number of branch pre-training epochs.")
    p.add_argument("--finetune_epochs", type=int, default=100, help="Maximum number of MTFNet joint fine-tuning epochs.")
    p.add_argument("--pretrain_lr", type=float, default=1e-3, help="Learning rate for branch pre-training.")
    p.add_argument("--finetune_lr", type=float, default=5e-4, help="Learning rate for joint fine-tuning.")
    p.add_argument("--weight_decay", type=float, default=1e-4, help="Adam weight decay.")
    p.add_argument("--patience", type=int, default=10, help="Early-stopping patience based on validation loss.")
    p.add_argument("--num_workers", type=int, default=0, help="Number of DataLoader worker processes.")
    p.add_argument("--bootstrap_n", type=int, default=1000, help="Number of bootstrap resamples for F1-score confidence intervals.")
    p.add_argument("--lite", action="store_true", help="Use a smaller network for quick workflow tests with the synthetic example data.")
    p.add_argument("--torch_threads", type=int, default=1, help="Number of PyTorch CPU threads. Set <=0 to leave unchanged.")
    return p


if __name__ == "__main__":
    run(parser().parse_args())
